name: 构建镜像并推送到Docker Hub

on: push

jobs:
  python-build:
    name: flask测试项目
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 登录Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: 构建并推送到Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: wufei222/cicd-test:${{ github.ref_name }}

      - name: 配置 AWS 凭据
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: 验证 AWS CLI 配置
        run: |
          aws sts get-caller-identity

      - name: 创建 .kube 目录
        run: mkdir -p $HOME/.kube

      - name: 设置 KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          echo "KUBECONFIG 内容如下:"
          cat $HOME/.kube/config

      - name: 更新 Kubernetes 部署
        run: |
          kubectl set image deployment/cicd-test-deployment cicd-test-container=wufei222/cicd-test:${{ github.ref_name }}
        env:
          KUBECONFIG: $HOME/.kube/config
